all:
  nameserver1: 8.8.8.8
  nameserver2: 8.8.8.8
  eth_device: enp0s8

  children:
    dataservers:
      hosts:
        192.168.100.101:
          ip_address: "192.168.100.101"

    webservers:
      hosts:
        192.168.100.102:
          ip_address: "192.168.100.102"

    workstations:
      hosts:
        192.168.100.103:
          ip_address: "192.168.100.103"
