---

- hosts: all
  become: true
  tags: always
  pre_tasks:
    - name: pre-run | cache update (apt)
      tags: always
      apt: update_cache=yes
      changed_when: false
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: pre-run | cache update (dnf)
      tags: always
      dnf: update_cache=yes
      changed_when: false
      when: ansible_distribution in ["CentOS"]

- hosts: all
  become: true
  roles:
    - role: system
