---

- hosts: all
  become: true
  tags: always
  pre_tasks:
    - name: cache update (apt)
      apt: update_cache=yes
      changed_when: false
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: cache update (dnf)
      dnf: update_cache=yes
      changed_when: false
      when: ansible_distribution in ["CentOS"]

- hosts: all
  become: true
  roles:
    - role: system
