---
title: "Dev Environment"
author: "Akhlak Mahmood"
---

Step-by-step guide to setting up your development environment for this project.

## Preparation

Make sure you have the following ready

1. Access to one of the group servers (tyrion, tyrion2 etc.)
2. Access to the [GitHub organization](https://github.com/Ramprasad-Group) as a member
3. Installed the GATech VPN software on your laptop/desktop

## Connection
If you are using one of our group servers

1. Login to GATech VPN
2. SSH into the server from your terminal
```sh
ssh <your_username>@<server>.mse.gatech.edu
```
3. If you haven't already, create a new SSH key and add it to your GitHub profile.
```sh
ssh-keygen
```
4. See [the GitHub help page](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account?platform=linux#adding-a-new-ssh-key-to-your-account) for more information about how to add your SSH key.

## Install Miniconda
We will use conda for environment and package management.

1. Download and install the correct version of miniconda for your OS from [the official website](https://docs.anaconda.com/free/miniconda/#latest-miniconda-installer-links).

2. **Note:** If you are using one of the group servers, you must enter `/data/<your_username>/miniconda3` as your installation path. Do not simply accept the default path.

::: callout-note
You should keep your `/home/<your_username>` directory clean.
Always install any large software (such as miniconda) on your `/data` directory. Your home directory usage must not exceed 15 GB at anytime.
:::


## Setup the Project
Set up your development environment by cloning the git repository and running the `make.sh` script in a bash terminal.

```sh
# Go to your data directory.
cd /data/<your_username>

# Clone the project.
git clone https://github.com/akhlakm/project

# Setup the environment.
cd project
source make.sh
```

## Setup VSCode
Download and install the latest version of VSCode for your OS from [the official website](https://code.visualstudio.com/download).
You should install the following VSCode extensions by searching for them in the extensions panel:

1. Remote SSH
2. Pylance
3. YAML
4. Quarto
5. Jupyter
6. Excel Viewer
7. Git Graph

You may also want to create/sign in to your VSCode account by clicking on the account button on the bottom left panel.
This will allow you to keep your settings synced between all your devices.
You can use your GitHub account to sign up.

## Connect your VSCode to the server
If you have installed the "Remote SSH" extension, your can use it to login to the group server via SSH.

1. Click on the `><` button located on the bottom left.
2. Add a new Host.
3. Enter the server address and your SSH username and password to login.
4. Open the project folder you cloned from GitHub [earlier](#setup-the-project) by entering it's path, e.g. `/data/<your_username>/project`
5. You can now open a new VSCode terminal by clicking `View > Terminal`.
6. Activate the environment from the terminal.
```sh
source make.sh
```

## Building Docs
You must document your works for reference purposes and writing manuscripts for publication in the future. We will use [Quarto](https://quarto.org/) for the documentation.

- To build the documentation, run the following from the VSCode terminal. Make sure the environment is active by sourcing the make.sh file first.
```sh
mk docs
```

- Open up your web browser to [http://localhost:8088](http://localhost:8088/) to view the built documentation.
